SELECT *
FROM employee;

SELECT EMP_NAME 사원명, SALARY 급여, BONUS 보너스, JOB_CODE 직급코드
FROM employee
WHERE BONUS IS NOT NULL;

SELECT *
FROM employee
WHERE EMAIL LIKE '__m%';
-- 와일드카드 기호를 값으로써 사용하고자 한다면 LIKE '__\_' ESCAPE '\'와 같이 작성해야 함!

SELECT COUNT(*)
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO, 8, 1) IN (2, 4);

SELECT TO_CHAR( SUM(SALARY), 'L99,999,999') 급여
FROM EMPLOYEE
WHERE ENT_YN ='N';

SELECT COUNT(*)
FROM EMPLOYEE
WHERE EXTRACT (MONTH FROM HIRE_DATE) = '09';


SELECT EMP_NAME, EMP_NO, JOB_CODE, DEPT_CODE, SALARY, BONUS
FROM EMPLOYEE
WHERE (JOB_CODE = 'J7' OR JOB_CODE = 'J6') AND (SALARY >= 2000000)
      AND (EMAIL LIKE '___#_%' ESCAPE '#') AND (BONUS IS NOT NULL) AND (SUBSTR(EMP_NO, 8, 1) IN (2, 4));